name: Deploy Staging

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: |
          docker build . --file Dockerfile --tag icomphub-web-app-staging:latest

      - name: Save Docker Image as .tar
        run: |
          docker save icomphub-web-app-staging:latest -o icomphub-web-app-staging.tar

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER01_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER01_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Docker Image to Server
        run: |
          scp icomphub-web-app-staging.tar ${{ secrets.SERVER01_USER }}@${{ secrets.SERVER01_HOST }}:/tmp/icomphub-web-app-staging.tar

      - name: Run Docker Image on VPS
        run: |
          ssh ${{ secrets.SERVER01_USER }}@${{ secrets.SERVER01_HOST }} << 'EOF'
            docker load -i /tmp/icomphub-web-app-staging.tar
            docker stop icomphub-web-app-staging || true
            docker rm icomphub-web-app-staging || true
            docker run -d --name icomphub-web-app-staging -p ${{ vars.WEB_APP_PORT_STAGING }}:3000 icomphub-web-app-staging:latest
          EOF
